### ISSUE TITLE
Roadmap for v0.2.0

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/react-native-debugger#1]
- [x] Support to set debugger host, port (#3)
- [x] Support to disable React DevTools / Redux DevTools
- [x] Create a patch to replace `open debugger-ui with Chrome` for React Native packager (#3)

**Comment by aksonov** [comment]
Great app!
Any plans to support great Mobx and their react dev tools https://github.com/mobxjs/mobx-react-devtools ?

**Comment by jhen0409** [comment]
@aksonov It's interesting, but I'm not yet familiar with Mbox, I'll find time to try it. Also, if you can help, I will be happy to accept. :)

**Comment by jhen0409** [comment]
@aksonov we can watching [mobx-remotedev](https://github.com/zalmoxisus/mobx-remotedev), maybe we can port it on here if remotedev version is completed. And I don't sure yet how to implement data dependencies & render highlight for mobx-react-devtools on React Native, it has too many DOM behaviors.

Also, this issue is out of date, closed now.
