### ISSUE TITLE
[iOS][macOS] Invoke dev menu methods by rndebugger

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/react-native-debugger#18]
The React Native for iOS have `NativeModules.DevMenu`, so we can invoke following methods on the worker:

* Reload JS
* ~~Enable LiveReload~~
* ~~Enable Hot Reload~~
* ~~Enable Profiling~~
* ~~Show Dev menu~~

I think it will be helpful to enhance the development experience, even we can support MacBook Touch Bar in the future.

Or we can invoke directly in `RNDebuggerWorker.js` context for console:

```js
global.require('NativeModules').DevMenu.reload();
```

## Others

* (Not iOS only, #15) Enable XHR Inspect 

## Roadmap

- [x] Check methods available by worker message
- [x] Add methods to menu or context menu, invoke by worker message
- [x] Touch Bar support for macOS (Upstream: https://github.com/electron/electron/issues/7781)
