### ISSUE TITLE
New `setupDevTools` method for React inspector

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/react-native-debugger#21]
Currently React inspector server port is `8097`, it can only accept one connection, that's why we still not support multi-device. (You can run `react-native start --port=8082` for start the second `react-native` instance)

Finally we got https://github.com/facebook/react-native/pull/10522 (It should land at 0.39), we can custom React inspector server port, but I hope it can __backward compatibility__, so a new `setupDevtools` might be better.

```js
// Internal use
setupDevtools(hostByWorkerMessage, portByWorkerMessage);
```

## Roadmap

- [ ] Get random port with [get-port](https://www.npmjs.com/package/get-port) for React inspector, it should with the `prepareJSRuntime` method for debugger.
- [ ] A `hostname` option for device (default is `localhost` & [Android automatic identification](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/setupDevtools.js#L20-L23))
- [ ] New `setupDevtools` method
- [ ] Support `New window` for multi-device (Include automatic start for `set-debugger-loc`)

**Comment by jhen0409** [comment]
Closing in favor of #63.
